const data = {
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/free-shirt.jpg',
      price: 7000,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countsInStock: 8,
      description: 'A popular shirt',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/fit-shirt.jpg',
      price: 8000,
      brand: 'Adidas',
      rating: 3.2,
      numReviews: 10,
      countsInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/slim-shirt.jpg',
      price: 8000,
      brand: 'Raymond',
      rating: 2.9,
      numReviews: 13,
      countsInStock: 15,
      description: 'A popular shirt',
    },
    {
      name: 'Golf Pants',
      slug: 'golf-pants',
      category: 'Pants',
      image: '/images/golf-pants.jpg',
      price: 12000,
      brand: 'Oliver',
      rating: 2.9,
      numReviews: 13,
      countsInStock: 15,
      description: 'Smart looking pants',
    },
    {
      name: 'Fit Pants',
      slug: 'fit-pants',
      category: 'Pants',
      image: '/images/fit-pant.jpg',
      price: 15000,
      brand: 'Zara',
      rating: 4.9,
      numReviews: 20,
      countsInStock: 20,
      description: 'Smart looking pants',
    },
    {
      name: 'Classic Pants',
      slug: 'classic-pants',
      category: 'Pants',
      image: '/images/classic-pant.jpg',
      price: 15000,
      brand: 'Tara',
      rating: 4.6,
      numReviews: 12,
      countsInStock: 10,
      description: 'Smart looking pants',
    },
  ],
};

export default data;
